site_name: My Docs

theme:
  name: "material"

watch:
- fair_mango

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [.]
        options:
          docstring_style: numpy

nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md
