name: release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
          cache: pip

      - name: Build release distributions
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v6
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - publish

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/fair-mango

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v7
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
